# Generated by Django 5.2.6 on 2025-12-30 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MfalmeUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('soldier_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('elite_rank', models.CharField(blank=True, default='Recruit', max_length=50)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('registration_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('registration_device', models.CharField(blank=True, max_length=200)),
                ('registration_location', models.CharField(blank=True, max_length=200)),
                ('trading_experience', models.CharField(blank=True, default='Beginner', max_length=50)),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferred_package', models.CharField(blank=True, max_length=100)),
                ('trading_platform', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('account_status', models.CharField(blank=True, default='pending', max_length=20)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('referral_code', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.mfalmeusers')),
            ],
            options={
                'verbose_name': 'Elite Soldier',
                'verbose_name_plural': 'Elite Soldiers',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('registration_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mfalmeusers')),
            ],
            options={
                'ordering': ['-registration_time'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mfalmeusers')),
            ],
            options={
                'verbose_name': 'Verification Code',
                'verbose_name_plural': 'Verification Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
