# Generated by Django 5.2.6 on 2026-01-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfalmeusers',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
