# Generated by Django 5.2.6 on 2026-02-16 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('market_analysis', 'Market Analysis'), ('trading_psychology', 'Trading Psychology'), ('options_strategies', 'Options Strategies'), ('forex_trading', 'Forex Trading'), ('company_news', 'Company News'), ('education', 'Education'), ('general', 'General')], default='general', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/thumbnails/')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('read_time', models.IntegerField(default=5)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pdfs/covers/')),
                ('pages', models.IntegerField(default=0)),
                ('file_size', models.CharField(blank=True, max_length=20)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('course_material', 'Course Material'), ('ebook', 'E-Book'), ('worksheet', 'Worksheet'), ('cheat_sheet', 'Cheat Sheet'), ('report', 'Market Report'), ('guide', 'Trading Guide'), ('other', 'Other')], default='other', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('access_level', models.CharField(choices=[('free', 'Free Access'), ('citizen', 'Citizen Tier'), ('studyhall', 'Study Hall Tier'), ('society', 'Society Tier'), ('paid', 'Paid Only')], default='free', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free', models.BooleanField(default=True)),
                ('downloads', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPDFAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='brokerage',
            options={'ordering': ['region', 'order']},
        ),
        migrations.AlterModelOptions(
            name='communitytier',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='educationprogram',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', 'category']},
        ),
        migrations.AlterModelOptions(
            name='mentorshipprogram',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='partnershipprogram',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sitecontent',
            options={'ordering': ['section']},
        ),
        migrations.AlterModelOptions(
            name='sitecontentversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'ordering': ['category', 'key']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-is_featured', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketreply',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingvideo',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usercommunitymembership',
            options={'ordering': ['-joined_at']},
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usereducationenrollment',
            options={'ordering': ['-enrolled_at']},
        ),
        migrations.AlterModelOptions(
            name='userpartnership',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-login_at']},
        ),
        migrations.AlterModelOptions(
            name='uservideoaccess',
            options={},
        ),
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='brokerage',
            name='myapp_broke_is_reco_fd41b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactsubmission',
            name='myapp_conta_priorit_3ad4ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='myapp_notif_created_92a5b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnershipprogram',
            name='myapp_partn_price_cfa21e_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='severity',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='account_types',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='supported_markets',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='communitytier',
            name='access_level',
            field=models.CharField(default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='communitytier',
            name='benefits',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='communitytier',
            name='color_scheme',
            field=models.CharField(default='blue', max_length=50),
        ),
        migrations.AlterField(
            model_name='communitytier',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='communitytier',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='priority',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='materials',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='badge_color',
            field=models.CharField(default='primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='curriculum',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='promo_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='total_hours',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='total_lessons',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='total_modules',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='benefits',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='package',
            name='payment_options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='partnershipprogram',
            name='benefits',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='partnershipprogram',
            name='color_class',
            field=models.CharField(default='bronze', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnershipprogram',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='partnershipprogram',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='partnershipprogram',
            name='risk_level',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='animation_delay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='color',
            field=models.CharField(default='primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='suffix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='satisfaction_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpartnership',
            name='duration_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.mfalmeusers'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_resources', to='myapp.course'),
        ),
        migrations.AddField(
            model_name='userpdfaccess',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='userpdfaccess',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pdf'),
        ),
        migrations.AddField(
            model_name='userpdfaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mfalmeusers'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status', 'created_at'], name='myapp_blog_status_cd1281_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['category', 'status'], name='myapp_blog_categor_679bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='myapp_blog_slug_6cc76a_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['is_active', 'created_at'], name='myapp_pdf_is_acti_34c15c_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['access_level', 'is_active'], name='myapp_pdf_access__ee6af4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpdfaccess',
            unique_together={('user', 'pdf')},
        ),
    ]
