# Generated by Django 5.0.4 on 2026-05-17 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_paymenttransaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='THE MIGHTY ELGUAGO', max_length=200)),
                ('subtitle', models.CharField(default='The Ultimate Roadmap to Financial Freedom', max_length=300)),
                ('author', models.CharField(default='Sir Levi Muriuki', max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(default='\n    Financial Markets, Strategy, Risk & Wealth Creation — A Complete Guide to Hands-On Financial Markets Experience.\n    \n    Crafted personally by Sir Levi Muriuki (CEO, Mfalme Betterdays Capital), "THE MIGHTY ELGUAGO" is the definitive guide to achieving financial freedom through hands-on market experience. This isn\'t just theory — it\'s the battle-tested framework forged through 13+ years of market victories and lessons.\n    ')),
                ('price_usd', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('price_kes', models.DecimalField(decimal_places=2, default=12900, max_digits=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('cover_s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('pdf_s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('pages', models.IntegerField(default=350)),
                ('language', models.CharField(default='English', max_length=50)),
                ('edition', models.CharField(default='First Edition', max_length=50)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('stock', models.IntegerField(default=1000)),
                ('preorder_stock', models.IntegerField(default=500)),
                ('sold_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('preorder', 'Pre-Order'), ('in_stock', 'In Stock'), ('sold_out', 'Sold Out'), ('coming_soon', 'Coming Soon')], default='preorder', max_length=20)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bonus_features', models.JSONField(blank=True, default=list, help_text='List of bonus features included')),
                ('features', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='myapp_book_status_ae0f01_idx'), models.Index(fields=['is_featured', 'is_active'], name='myapp_book_is_feat_633ddb_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_type', models.CharField(choices=[('digital', 'Digital Download Only'), ('physical', 'Physical + Digital')], default='digital', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(default='sasapay', max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('digital_access_granted', models.BooleanField(default=False)),
                ('digital_access_code', models.CharField(blank=True, max_length=50, null=True)),
                ('digital_access_expires', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.book')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='myapp_booko_order_n_ba484e_idx'), models.Index(fields=['status', 'created_at'], name='myapp_booko_status_ad924e_idx'), models.Index(fields=['customer_email'], name='myapp_booko_custome_72b3e6_idx')],
            },
        ),
    ]
