# Generated by Django 5.2.6 on 2026-02-17 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blog_pdf_userpdfaccess_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='myapp.course'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Select which course this video belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('market_consultation', 'Market Consultation'), ('lifetime_mentorship', 'Lifetime Mentorship'), ('leveraging_package', 'Leveraging Package'), ('education_program', 'Education Program'), ('partnership', 'Partnership Program'), ('subscription', 'Subscription'), ('deposit', 'Account Deposit'), ('withdrawal', 'Withdrawal'), ('course_purchase', 'Course Purchase'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'created_at'], name='myapp_cours_is_acti_4d796e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['course', 'status'], name='myapp_payme_course__334f24_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['course', 'is_active'], name='myapp_pdf_course__f7438c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingvideo',
            index=models.Index(fields=['course', 'is_active'], name='myapp_train_course__6716e6_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['user', 'course'], name='myapp_userc_user_id_58525d_idx'),
        ),
        migrations.AddIndex(
            model_name='userpdfaccess',
            index=models.Index(fields=['user', 'pdf'], name='myapp_userp_user_id_d52148_idx'),
        ),
        migrations.AddIndex(
            model_name='uservideoaccess',
            index=models.Index(fields=['user', 'video'], name='myapp_userv_user_id_1be614_idx'),
        ),
    ]
