# Generated by Django 5.0.4 on 2026-05-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_bookorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='access_code',
            new_name='paystack_access_code',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='pesapal_tracking_id',
            new_name='paystack_reference',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='pesapal_payment_method',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='pesapal_raw_response',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='sasapay_checkout_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='sasapay_payment_method',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='sasapay_raw_response',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='sasapay_status',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='sasapay_transaction_id',
        ),
        migrations.AddField(
            model_name='bookorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchandiseorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registration'), ('PROFILE_UPDATE', 'Profile Updated'), ('PASSWORD_CHANGE', 'Password Changed'), ('EMAIL_VERIFICATION', 'Email Verified'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PAYMENT_FAILED', 'Payment Failed'), ('COURSE_ENROLLED', 'Course Enrolled'), ('COURSE_COMPLETED', 'Course Completed'), ('MENTORING_BOOKED', 'Mentoring Booked'), ('COMMUNITY_JOINED', 'Community Joined'), ('COMMUNITY_REQUEST', 'Community Request'), ('SUPPORT_TICKET_CREATED', 'Support Ticket Created'), ('SUPPORT_TICKET_UPDATED', 'Support Ticket Updated'), ('SETTINGS_UPDATE', 'Settings Updated'), ('WATCHLIST_ADD', 'Added to Watchlist'), ('WATCHLIST_REMOVE', 'Removed from Watchlist'), ('INSTITUTE_APPLY', 'Institute Application'), ('ADMIN_ACTION', 'Admin Action'), ('SECURITY_EVENT', 'Security Event'), ('COURSE_ACCESS_EXPIRED', 'Course Access Expired'), ('PDF_VIEWED', 'PDF Viewed'), ('VIDEO_WATCHED', 'Video Watched'), ('TICKET_PURCHASED', 'Ticket Purchased'), ('MERCHANDISE_PURCHASED', 'Merchandise Purchased'), ('BOOK_PURCHASED', 'Book Purchased')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='payment_method',
            field=models.CharField(default='paystack', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='payment_method',
            field=models.CharField(default='paystack', max_length=50),
        ),
        migrations.AlterField(
            model_name='merchandiseorder',
            name='payment_method',
            field=models.CharField(default='paystack', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('merchandise', 'Merchandise'), ('package', 'Package'), ('book', 'Book')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='paystack', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('KES', 'Kenyan Shilling')], default='KES', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('mpesa', 'M-Pesa via Paystack'), ('card', 'Card via Paystack'), ('bank_transfer', 'Bank Transfer'), ('manual', 'Manual Payment')], default='paystack', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('market_consultation', 'Market Consultation'), ('lifetime_mentorship', 'Lifetime Mentorship'), ('leveraging_package', 'Leveraging Package'), ('education_program', 'Education Program'), ('partnership', 'Partnership Program'), ('subscription', 'Subscription'), ('deposit', 'Account Deposit'), ('withdrawal', 'Withdrawal'), ('course_purchase', 'Course Purchase'), ('ticket', 'Event Ticket'), ('merchandise', 'Merchandise'), ('book', 'Book Purchase'), ('video_purchase', 'Video Purchase'), ('pdf_purchase', 'PDF Purchase'), ('package_purchase', 'Package Purchase'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Support'), ('billing', 'Billing/Payment'), ('account', 'Account Issues'), ('education', 'Education Programs'), ('packages', 'Packages'), ('community', 'Community Access'), ('partnership', 'Partnership'), ('institute', 'Institute'), ('tickets', 'Event Tickets'), ('merchandise', 'Merchandise'), ('books', 'Books'), ('other', 'Other')], default='general', max_length=50),
        ),
    ]
