# Generated by Django 5.2.6 on 2026-02-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_paymenttransaction_course_trainingvideo_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_12_months',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for 12 months access', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='price_1_month',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for 1 month access', max_digits=10),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='purchase_type',
            field=models.CharField(choices=[('1_month', '1 Month Access'), ('12_months', '12 Months Access')], default='1_month', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['access_expires_at'], name='myapp_userc_access__dbbc4b_idx'),
        ),
    ]
