# Generated by Django 5.2.6 on 2026-02-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_course_price_12_months_course_price_1_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='materials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
