# Generated by Django 5.0.4 on 2026-06-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_access_code_paymenttransaction_paystack_access_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='eventticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='payment_method',
            field=models.CharField(default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='unit_price_kes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='unit_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'date'], name='myapp_event_is_acti_9a5282_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['featured', 'is_active'], name='myapp_event_feature_ed1500_idx'),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['ticket_number'], name='myapp_event_ticket__2f4bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['attendee_email'], name='myapp_event_attende_0de5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['attendee_phone'], name='myapp_event_attende_4134c3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['event', 'status'], name='myapp_event_event_i_380b9b_idx'),
        ),
    ]
