# Generated by Django 5.0.4 on 2026-06-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_event_options_alter_eventticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_price_kes',
            field=models.DecimalField(decimal_places=2, default=32121, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price_usd',
            field=models.DecimalField(decimal_places=2, default=249, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('mpesa', 'M-PESA'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('free', 'Free')], default='paystack', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='unit_price_kes',
            field=models.DecimalField(decimal_places=2, default=32121, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='unit_price_usd',
            field=models.DecimalField(decimal_places=2, default=249, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['payment_reference'], name='myapp_event_payment_6f9913_idx'),
        ),
    ]
