# Generated by Django 5.0.4 on 2026-06-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_event_ticket_price_kes_alter_event_ticket_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='headway_account',
            field=models.CharField(blank=True, help_text='Headway Broker Account Number (e.g., 16882297)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price_kes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='payment_method',
            field=models.CharField(choices=[('free', 'Free Registration'), ('paystack', 'Paystack'), ('mpesa', 'M-PESA'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('refunded', 'Refunded')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='unit_price_kes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='unit_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['headway_account'], name='myapp_event_headway_6656fd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['created_at'], name='myapp_event_created_940a4f_idx'),
        ),
    ]
