# Generated by Django 5.2.6 on 2026-02-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_course_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
