# Generated by Django 5.2.6 on 2026-02-17 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitytier',
            name='required_courses',
            field=models.JSONField(blank=True, default=list, help_text='List of course IDs required'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registration'), ('PROFILE_UPDATE', 'Profile Updated'), ('PASSWORD_CHANGE', 'Password Changed'), ('EMAIL_VERIFICATION', 'Email Verified'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PAYMENT_FAILED', 'Payment Failed'), ('COURSE_ENROLLED', 'Course Enrolled'), ('COURSE_COMPLETED', 'Course Completed'), ('MENTORING_BOOKED', 'Mentoring Booked'), ('COMMUNITY_JOINED', 'Community Joined'), ('COMMUNITY_REQUEST', 'Community Request'), ('SUPPORT_TICKET_CREATED', 'Support Ticket Created'), ('SUPPORT_TICKET_UPDATED', 'Support Ticket Updated'), ('SETTINGS_UPDATE', 'Settings Updated'), ('WATCHLIST_ADD', 'Added to Watchlist'), ('WATCHLIST_REMOVE', 'Removed from Watchlist'), ('INSTITUTE_APPLY', 'Institute Application'), ('ADMIN_ACTION', 'Admin Action'), ('SECURITY_EVENT', 'Security Event')], max_length=50),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Support'), ('billing', 'Billing/Payment'), ('account', 'Account Issues'), ('education', 'Education Programs'), ('packages', 'Packages'), ('community', 'Community Access'), ('partnership', 'Partnership'), ('institute', 'Institute'), ('other', 'Other')], default='general', max_length=50),
        ),
        migrations.CreateModel(
            name='CommunityJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('met_requirements', models.BooleanField(default=False)),
                ('investment_at_request', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('courses_completed', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='myapp.communitytier')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_community_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='myapp_commu_status_32a873_idx'), models.Index(fields=['user', 'status'], name='myapp_commu_user_id_f9fe27_idx')],
                'unique_together': {('user', 'community')},
            },
        ),
        migrations.CreateModel(
            name='InstituteApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('info_needed', 'More Info Needed')], default='pending', max_length=20)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trading_experience', models.CharField(choices=[('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-10', '5-10 years'), ('10+', '10+ years')], max_length=10)),
                ('proof_of_funds', models.FileField(upload_to='institute/proof_of_funds/')),
                ('trading_history', models.FileField(blank=True, null=True, upload_to='institute/trading_history/')),
                ('notes', models.TextField(blank=True, help_text='Additional information from applicant')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this application')),
                ('notified', models.BooleanField(default=False, help_text='Has the user been notified of decision?')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['status', 'applied_at'], name='myapp_insti_status_6e3e92_idx'), models.Index(fields=['user', 'status'], name='myapp_insti_user_id_291c94_idx')],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('course', 'Course'), ('package', 'Package')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'content_type'], name='myapp_watch_user_id_95619f_idx')],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
    ]
