# Generated by Django 5.2.6 on 2026-02-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_communitytier_required_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingvideo',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Custom embed code for video player', null=True),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, WebM, etc.)', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video (Vimeo, YouTube, etc.) - leave empty if uploading file', null=True),
        ),
        migrations.AddIndex(
            model_name='trainingvideo',
            index=models.Index(fields=['category'], name='myapp_train_categor_b5aa1b_idx'),
        ),
    ]
