# Generated by Django 5.2.6 on 2026-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_trainingvideo_embed_code_trainingvideo_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='unique_viewers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpdfaccess',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpdfaccess',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpdfaccess',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registration'), ('PROFILE_UPDATE', 'Profile Updated'), ('PASSWORD_CHANGE', 'Password Changed'), ('EMAIL_VERIFICATION', 'Email Verified'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PAYMENT_FAILED', 'Payment Failed'), ('COURSE_ENROLLED', 'Course Enrolled'), ('COURSE_COMPLETED', 'Course Completed'), ('MENTORING_BOOKED', 'Mentoring Booked'), ('COMMUNITY_JOINED', 'Community Joined'), ('COMMUNITY_REQUEST', 'Community Request'), ('SUPPORT_TICKET_CREATED', 'Support Ticket Created'), ('SUPPORT_TICKET_UPDATED', 'Support Ticket Updated'), ('SETTINGS_UPDATE', 'Settings Updated'), ('WATCHLIST_ADD', 'Added to Watchlist'), ('WATCHLIST_REMOVE', 'Removed from Watchlist'), ('INSTITUTE_APPLY', 'Institute Application'), ('ADMIN_ACTION', 'Admin Action'), ('SECURITY_EVENT', 'Security Event'), ('COURSE_ACCESS_EXPIRED', 'Course Access Expired'), ('PDF_VIEWED', 'PDF Viewed'), ('VIDEO_WATCHED', 'Video Watched')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='downloads',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='allow_download',
            field=models.BooleanField(default=False, help_text='Allow users to download this video'),
        ),
        migrations.AlterField(
            model_name='userpdfaccess',
            name='download_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='userpdfaccess',
            name='downloaded',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='userpdfaccess',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['is_active', 'access_expires_at'], name='myapp_userc_is_acti_0f6f90_idx'),
        ),
    ]
