# Generated by Django 5.2.6 on 2026-02-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_pdf_unique_viewers_usercourse_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='pesapal_payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='pesapal_raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='pesapal_tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('mpesa', 'M-Pesa'), ('bitcoin', 'Bitcoin'), ('usdt', 'USDT'), ('bank_transfer', 'Bank Transfer'), ('equity_bank', 'Equity Bank'), ('manual', 'Manual Payment'), ('paystack', 'Paystack'), ('pesapal', 'Pesapal'), ('mpesa', 'M-PESA'), ('bank', 'Bank Transfer'), ('card', 'Card')], default='paystack', max_length=20),
        ),
    ]
