# Generated by Django 5.0.4 on 2024-05-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_mfalmeusers_payments_delete_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfalmeusers',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='mfalmeusers',
            name='secondname',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='courseId',
        ),
    ]
