# Generated by Django 5.0.4 on 2024-05-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_mfalmeusers_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfalmeusers',
            name='phones',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
