# Generated by Django 5.0.4 on 2024-05-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_mfalmeusers_phones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfalmeusers',
            name='phones',
        ),
    ]
