# Generated by Django 4.x on 2026-02-22
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0013_paymenttransaction_sasapay_checkout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpdfaccess',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpdfaccess',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]