# Generated by Django 5.0.4 on 2024-05-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_mfalmeusers_phones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='amountusd',
        ),
    ]
