# Generated by Django 5.2.6 on 2026-02-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_add_viewed_field_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpdfaccess',
            name='viewed_at',
        ),
    ]
