# Generated by Django 5.0.4 on 2024-05-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_payments_amountusd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='amountkes',
            new_name='amountusd',
        ),
    ]
