# Generated by Django 5.2.6 on 2026-03-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_userpdfaccess_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingvideo',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video (Vimeo, YouTube, etc.) - leave empty if uploading file', max_length=500, null=True),
        ),
    ]
