# Generated by Django 5.2.6 on 2026-03-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_trainingvideo_allow_download_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingvideo',
            name='title',
            field=models.TextField(),
        ),
    ]
