# Generated by Django 5.0.4 on 2024-05-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_amountkes_payments_amountusd'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='keprice',
            field=models.FloatField(default=0.0),
        ),
    ]
