# Generated by Django 5.2.6 on 2026-03-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_unlimited_title_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingvideo',
            name='s3_key',
            field=models.CharField(blank=True, help_text='S3 key for videos uploaded directly to S3', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='thumbnail_s3_key',
            field=models.CharField(blank=True, help_text='S3 key for thumbnails uploaded directly to S3', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video (Vimeo, YouTube, etc.) OR S3 key from direct upload', max_length=1000, null=True),
        ),
    ]
