# Generated by Django 5.0.4 on 2024-05-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_products_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='amountusd',
            new_name='priceusd',
        ),
    ]
