# Generated by Django 5.2.6 on 2026-03-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_trainingvideo_s3_key_trainingvideo_thumbnail_s3_key_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trainingvideo',
            name='myapp_train_course__6716e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingvideo',
            name='myapp_train_categor_b5aa1b_idx',
        ),
        migrations.RemoveField(
            model_name='trainingvideo',
            name='embed_code',
        ),
        migrations.RemoveField(
            model_name='trainingvideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='external_url',
            field=models.URLField(blank=True, help_text='External URL (YouTube, Vimeo, etc.)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='s3_key',
            field=models.CharField(blank=True, help_text='S3 key for videos uploaded directly to S3 (e.g., videos/20260310_123456_test.mp4)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file directly (not recommended for large files)', null=True, upload_to='videos/'),
        ),
    ]
