# Generated by Django 5.0.4 on 2024-05-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_amountusd_products_priceusd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.URLField(),
        ),
    ]
