# Generated by Django 5.2.6 on 2026-03-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_trainingvideo_myapp_train_course__6716e6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingvideo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='is_free',
            field=models.BooleanField(default=False, help_text='If checked, video is free for everyone'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='module',
            field=models.CharField(blank=True, help_text="Module or chapter name (e.g., 'Chapter 1', 'Module 3')", max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='trainingvideo',
            index=models.Index(fields=['course', 'order'], name='myapp_train_course__482608_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingvideo',
            index=models.Index(fields=['category', 'is_active'], name='myapp_train_categor_45285e_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingvideo',
            index=models.Index(fields=['s3_key'], name='myapp_train_s3_key_34719e_idx'),
        ),
    ]
