# Generated by Django 5.2.6 on 2026-03-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_trainingvideo_is_featured_trainingvideo_is_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_s3_key',
            field=models.CharField(blank=True, help_text='S3 key for thumbnail uploaded directly to S3 (e.g., course_thumbnails/20260311_123456_abc123_image.jpg)', max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['thumbnail_s3_key'], name='myapp_cours_thumbna_b1018c_idx'),
        ),
    ]
