# Generated by Django 5.2.6 on 2026-03-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_course_thumbnail_s3_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='cover_s3_key',
            field=models.CharField(blank=True, help_text='S3 key for cover image uploaded directly to S3', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='pdf_s3_key',
            field=models.CharField(blank=True, help_text='S3 key for PDF uploaded directly to S3 (e.g., pdfs/20260311_123456_abc123_document.pdf)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['pdf_s3_key'], name='myapp_pdf_pdf_s3__af89cc_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['cover_s3_key'], name='myapp_pdf_cover_s_268ca1_idx'),
        ),
    ]
