# Generated by Django 5.0.4 on 2024-05-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_journals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
