# Generated by Django 5.0.4 on 2026-04-21 19:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_event_merchandisecategory_cartsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('apparel', 'Apparel'), ('accessories', 'Accessories'), ('tools', 'Tools'), ('books', 'Books')], default='apparel', max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('image_key', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('item_type', models.CharField(choices=[('ticket', 'Ticket'), ('merchandise', 'Merchandise'), ('package', 'Package')], max_length=50)),
                ('items', models.JSONField(default=list)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='sasapay', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='merchandiseitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='payment_transaction',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='event',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='merchandiseorder',
            options={},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='remaining_tickets',
            new_name='current_bookings',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='is_upcoming',
            new_name='featured',
        ),
        migrations.RenameField(
            model_name='merchandiseorder',
            old_name='shipping_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='merchandiseorder',
            old_name='shipping_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='merchandiseorder',
            old_name='shipping_phone',
            new_name='customer_phone',
        ),
        migrations.RenameField(
            model_name='merchandiseorder',
            old_name='shipping_address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='merchandiseorder',
            old_name='tracking_number',
            new_name='order_reference',
        ),
        migrations.RenameField(
            model_name='merchandiseorder',
            old_name='shipping_cost_kes',
            new_name='shipping_cost',
        ),
        migrations.RenameField(
            model_name='merchandiseorder',
            old_name='shipping_cost_usd',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='merchandiseorder',
            old_name='subtotal_kes',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='event',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='event',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='event',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_revenue',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_tickets_sold',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='guest_phone',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='payment_transaction',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='shipped_at',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='shipping_postal_code',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='subtotal_usd',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='total_kes',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='total_usd',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='tracking_url',
        ),
        migrations.RemoveField(
            model_name='merchandiseorder',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 7, 9, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='event',
            name='poster_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='poster_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price_usd',
            field=models.DecimalField(decimal_places=2, default=249, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='East & Central Africa Live Leveraging Summit', max_length=200),
        ),
        migrations.AddField(
            model_name='merchandiseorder',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='merchandiseorder',
            name='payment_method',
            field=models.CharField(default='sasapay', max_length=50),
        ),
        migrations.AddField(
            model_name='merchandiseorder',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='The biggest trading event in East & Central Africa'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Safari Park Hotel, Nairobi', max_length=300),
        ),
        migrations.AlterField(
            model_name='merchandiseorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='merchandiseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('attendee_name', models.CharField(max_length=200)),
                ('attendee_phone', models.CharField(max_length=20)),
                ('attendee_email', models.EmailField(max_length=254)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, default=249, max_digits=10)),
                ('unit_price_kes', models.DecimalField(decimal_places=2, default=31872, max_digits=10)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(default='sasapay', max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('order_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='pending', max_length=20)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='myapp.event')),
            ],
        ),
        migrations.DeleteModel(
            name='CartSession',
        ),
        migrations.DeleteModel(
            name='MerchandiseCategory',
        ),
        migrations.DeleteModel(
            name='MerchandiseItem',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='TicketOrder',
        ),
        migrations.DeleteModel(
            name='TicketPurchase',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
