# Generated by Django 5.0.4 on 2024-06-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_eventspayments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
