# Generated by Django 5.0.4 on 2024-06-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_availabletickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspayments',
            name='no_of_tickets',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='eventspayments',
            name='tickets_number',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
