# Generated by Django 5.0.4 on 2024-06-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_eventspayments_no_of_tickets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventspayments',
            old_name='no_of_tickets',
            new_name='no_of_seats',
        ),
    ]
