# Generated by Django 5.0.4 on 2024-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_no_of_tickets_eventspayments_no_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspayments',
            name='no_of_seats',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventspayments',
            name='tickets_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
